name: Docker Build
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ethanscully
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ethanscully/shepherd:latest \
          -t ethanscully/shepherd:${GITHUB_REF_NAME#v} \
          --push .
